/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alexios Apokaukos (https://sketchfab.com/Alexios_Apokaukos)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/triumph-spitfire-mkiii-9c5c1a73f65046459051f9d0bf1132a0
title: Triumph Spitfire MKIII
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model({ ...props }) {
  const { nodes, materials } = useGLTF("./triumph_spitfire_mkiii.glb");
  return (
    <group {...props} dispose={null} scale={1}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.11, 0.67, 0.42]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.TRIUMPH_SPITFIRE_CHROME}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.steeringwheel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.carbody}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.TRIUMPH_SPITFIRE_DASHBOARD}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.headlight_light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.number_plate}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.number_plate}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.TRIUMPH_SPITFIRE_WINDOWS}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.tire}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.wheel_rimrim}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials.TRIUMPH_SPITFIRE_floor}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.underbody}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials.leather}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials.HEADLIGHT_glass}
            />
          </group>
          <group
            position={[-0.64, 0.88, 0.39]}
            rotation={[0.71, -0.57, -0.28]}
            scale={[4.51, 0.93, 1.26]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.wheel_rimrim}
            />
          </group>
          <group position={[0.11, 0.67, 0.45]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials.TRIUMPH_SPITFIRE_CHROME}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials.number_plate}
            />
          </group>
          <group position={[0.11, 0.67, 0.42]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_30.geometry}
              material={materials["underbody.001"]}
            />
          </group>
          <group
            position={[-0.21, 0.27, -1.82]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials.TRIUMPH_SPITFIRE_CHROME}
            />
          </group>
          <group position={[0.32, 0.67, 0.42]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_34.geometry}
              material={materials.TRIUMPH_SPITFIRE_CHROME}
            />
          </group>
          <group
            position={[-0.66, 0.32, 1.34]}
            rotation={[Math.PI / 2, -0.02, 0]}
          >
            <group
              position={[0.01, 0, -0.05]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_37.geometry}
                material={materials["28_int_gauges"]}
              />
            </group>
            <group
              position={[0.67, -1.34, 0.31]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_39.geometry}
                material={materials.headglass}
              />
            </group>
            <group
              position={[0.67, -3.75, 0.33]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_41.geometry}
                material={materials.tire}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./triumph_spitfire_mkiii.glb");
